name: MyTriggeredAction

on: 
  push:
    branches:
      - dev

jobs:
  
  build:
    name: Builds on ssh
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application on server
        uses: appleboy/ssh-action@v1.0.3
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REGION: ${{ secrets.REGION }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          PRIVATE_KEY: ${{ secrets.INSTANCE_PRIVATE_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT}}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          envs: SLACK_TOKEN,ACCESS_KEY,SECRET_KEY,REGION,SSH_PORT,PRIVATE_KEY
          script: |
            sudo yum update 
            sudo yum install git -y
            sudo yum install python3 -y
            sudo yum install python3-pip -y
            sudo yum install ansible -y
            git clone https://github.com/EugeneSaju/project_webapp.git
            cd project_webapp/Deployment/playbooks/
            chmod +x program.py
            python3 python_pgm.py
            cd ~
            rm -rf project_webapp/
